services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - PORT=3333
    volumes:
      - dbdata:/usr/src/app
    restart: unless-stopped

volumes:
  dbdata:
